from turtle import *
bgcolor("#303030")
def draw_tectangle(width, height, Color):
    color(Color)
    begin_fill()
    for _ in range(2):
        forward(width)
        right(90)
        forward(height)
        right(90)
    end_fill()
if __name__ == '__name__':
    speed('show')
penup()
goto(-300, 150)
pendown()
draw_tectangle(300, 300, "green")
penup()
goto(0, 150)
pendown()
draw_tectangle(300, 300, "#ffffff")
color("red")
left(120)
up()
goto(90, 50)
down()
begin_fill()
circle(100, 300)
right(10)
circle(80, -275)
end_fill()
up()
goto(0, 30)
down()
setheading(0)
right(15)
begin_fill()
for i in range(5):
    forward(105)
    right(144)
end_fill()
up()
left(15)
goto(-500, 185)
down()
hideturtle()
done()
